In [1]:
conda list

# packages in environment at /home/hamdi_ug/anaconda3/envs/strgn:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
argon2-cffi               20.1.0           py36h8c4c3a4_1    conda-forge
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
blas                      1.0                         mkl  
bleach                    3.1.5              pyh9f0ad1d_0    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2020.6.24                     0    anaconda
certifi                   2020.6.20                py36_0    anaconda
cffi                      1.14.1           py36h0ff685e_0    conda-forge
cudatoolkit      

In [5]:
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '4'
# import torch

# os.environ['CUDA_VISIBLE_DEVICES'] = '4'

# use_cuda = torch.cuda.is_available()
# device = torch.device("cuda:0" if use_cuda else "cpu")

# Align Images using the main.py script with arg: --mode align

In [10]:
# !python main.py --mode align \
#                --inp_dir assets/representative/custom/male \
#                --out_dir assets/representative/celeba_hq/src/male

Namespace(batch_size=8, beta1=0.0, beta2=0.99, checkpoint_dir='expr/checkpoints', ds_iter=100000, eval_dir='expr/eval', eval_every=50000, f_lr=1e-06, hidden_dim=512, img_size=256, inp_dir='assets/representative/custom/male', lambda_cyc=1, lambda_ds=1, lambda_reg=1, lambda_sty=1, latent_dim=16, lm_path='expr/checkpoints/celeba_lm_mean.npz', lr=0.0001, mode='align', num_domains=2, num_outs_per_domain=10, num_workers=4, out_dir='assets/representative/celeba_hq/src/male', print_every=10, randcrop_prob=0.5, ref_dir='assets/representative/celeba_hq/ref', result_dir='expr/results', resume_iter=0, sample_dir='expr/samples', sample_every=5000, save_every=10000, seed=777, src_dir='assets/representative/celeba_hq/src', style_dim=64, total_iters=100000, train_img_dir='data/celeba_hq/train', val_batch_size=32, val_img_dir='data/celeba_hq/val', w_hpf=1, weight_decay=0.0001, wing_path='expr/checkpoints/wing.ckpt')
Number of parameters of generator: 43467395
Number of parameters of mapping_network: 24

In [5]:
# !python main.py --mode eval --num_domains 2 --resume_iter 100000 --w_hpf 1 \
#                 --checkpoint_dir expr/checkpoints/celeba_hq \
#                 --result_dir my_experiment/results \
#                 --src_dir my_experiment/src \
#                 --ref_dir my_experiment/ref

Namespace(batch_size=8, beta1=0.0, beta2=0.99, checkpoint_dir='expr/checkpoints/celeba_hq', ds_iter=100000, eval_dir='expr/eval', eval_every=50000, f_lr=1e-06, hidden_dim=512, img_size=256, inp_dir='assets/representative/custom/female', lambda_cyc=1, lambda_ds=1, lambda_reg=1, lambda_sty=1, latent_dim=16, lm_path='expr/checkpoints/celeba_lm_mean.npz', lr=0.0001, mode='eval', num_domains=2, num_outs_per_domain=10, num_workers=4, out_dir='assets/representative/celeba_hq/src/female', print_every=10, randcrop_prob=0.5, ref_dir='my_experiment/ref', result_dir='my_experiment/results', resume_iter=100000, sample_dir='expr/samples', sample_every=5000, save_every=10000, seed=777, src_dir='my_experiment/src', style_dim=64, total_iters=100000, train_img_dir='data/celeba_hq/train', val_batch_size=32, val_img_dir='data/celeba_hq/val', w_hpf=1.0, weight_decay=0.0001, wing_path='expr/checkpoints/wing.ckpt')
Number of parameters of generator: 43467395
Number of parameters of mapping_network: 2438272
N

In [16]:
def subdirs(dname):
    return [d for d in os.listdir(dname)
            if os.path.isdir(os.path.join(dname, d)) and d != '.ipynb_checkpoints']

In [17]:
subdirs('./my_experiment/src')

['male', 'female']

In [3]:
# !python main.py --mode sample --num_domains 2 --resume_iter 100000 --w_hpf 1 \
#                 --checkpoint_dir expr/checkpoints/celeba_hq \
#                 --result_dir my_experiment/results \
#                 --src_dir my_experiment/src \
#                 --ref_dir my_experiment/ref

Namespace(batch_size=8, beta1=0.0, beta2=0.99, checkpoint_dir='expr/checkpoints/celeba_hq', ds_iter=100000, eval_dir='expr/eval', eval_every=50000, f_lr=1e-06, hidden_dim=512, img_size=256, inp_dir='assets/representative/custom/female', lambda_cyc=1, lambda_ds=1, lambda_reg=1, lambda_sty=1, latent_dim=16, lm_path='expr/checkpoints/celeba_lm_mean.npz', lr=0.0001, mode='sample', num_domains=2, num_outs_per_domain=10, num_workers=4, out_dir='assets/representative/celeba_hq/src/female', print_every=10, randcrop_prob=0.5, ref_dir='my_experiment/ref', result_dir='my_experiment/results', resume_iter=100000, sample_dir='expr/samples', sample_every=5000, save_every=10000, seed=777, src_dir='my_experiment/src', style_dim=64, total_iters=100000, train_img_dir='data/celeba_hq/train', val_batch_size=32, val_img_dir='data/celeba_hq/val', w_hpf=1.0, weight_decay=0.0001, wing_path='expr/checkpoints/wing.ckpt')
Number of parameters of generator: 43467395
Number of parameters of mapping_network: 2438272

In [4]:
# !python main.py --mode sample --num_domains 2 --resume_iter 100000 --w_hpf 1 \
#                 --checkpoint_dir expr/checkpoints/celeba_hq \
#                 --result_dir my_experiment/results \
#                 --src_dir my_experiment/src \
#                 --ref_dir my_experiment/ref

Namespace(batch_size=8, beta1=0.0, beta2=0.99, checkpoint_dir='expr/checkpoints/celeba_hq', ds_iter=100000, eval_dir='expr/eval', eval_every=50000, f_lr=1e-06, hidden_dim=512, img_size=256, inp_dir='assets/representative/custom/female', lambda_cyc=1, lambda_ds=1, lambda_reg=1, lambda_sty=1, latent_dim=16, lm_path='expr/checkpoints/celeba_lm_mean.npz', lr=0.0001, mode='sample', num_domains=2, num_outs_per_domain=10, num_workers=4, out_dir='assets/representative/celeba_hq/src/female', print_every=10, randcrop_prob=0.5, ref_dir='my_experiment/ref', result_dir='my_experiment/results', resume_iter=100000, sample_dir='expr/samples', sample_every=5000, save_every=10000, seed=777, src_dir='my_experiment/src', style_dim=64, total_iters=100000, train_img_dir='data/celeba_hq/train', val_batch_size=32, val_img_dir='data/celeba_hq/val', w_hpf=1.0, weight_decay=0.0001, wing_path='expr/checkpoints/wing.ckpt')
Number of parameters of generator: 43467395
Number of parameters of mapping_network: 2438272

In [2]:
os.environ['CUDA_VISIBLE_DEVICES'] = ''

# With average faces

In [7]:
!python main.py --mode sample --num_domains 2 --resume_iter 100000 --w_hpf 1 \
                --checkpoint_dir expr/checkpoints/celeba_hq \
                --result_dir my_experiment/results \
                --src_dir my_experiment/src \
                --ref_dir my_experiment/ref

Namespace(batch_size=8, beta1=0.0, beta2=0.99, checkpoint_dir='expr/checkpoints/celeba_hq', ds_iter=100000, eval_dir='expr/eval', eval_every=50000, f_lr=1e-06, hidden_dim=512, img_size=256, inp_dir='assets/representative/custom/female', lambda_cyc=1, lambda_ds=1, lambda_reg=1, lambda_sty=1, latent_dim=16, lm_path='expr/checkpoints/celeba_lm_mean.npz', lr=0.0001, mode='sample', num_domains=2, num_outs_per_domain=10, num_workers=4, out_dir='assets/representative/celeba_hq/src/female', print_every=10, randcrop_prob=0.5, ref_dir='my_experiment/ref', result_dir='my_experiment/results', resume_iter=100000, sample_dir='expr/samples', sample_every=5000, save_every=10000, seed=777, src_dir='my_experiment/src', style_dim=64, total_iters=100000, train_img_dir='data/celeba_hq/train', val_batch_size=32, val_img_dir='data/celeba_hq/val', w_hpf=1.0, weight_decay=0.0001, wing_path='expr/checkpoints/wing.ckpt')
Number of parameters of generator: 43467395
Number of parameters of mapping_network: 2438272

** np.asarray(y) - 1

# First successful execution

In [4]:
!python main.py --mode sample --num_domains 2 --resume_iter 100000 --w_hpf 1 \
                --checkpoint_dir expr/checkpoints/celeba_hq \
                --result_dir my_experiment/results \
                --src_dir my_experiment/src \
                --ref_dir my_experiment/ref

Namespace(batch_size=8, beta1=0.0, beta2=0.99, checkpoint_dir='expr/checkpoints/celeba_hq', ds_iter=100000, eval_dir='expr/eval', eval_every=50000, f_lr=1e-06, hidden_dim=512, img_size=256, inp_dir='assets/representative/custom/female', lambda_cyc=1, lambda_ds=1, lambda_reg=1, lambda_sty=1, latent_dim=16, lm_path='expr/checkpoints/celeba_lm_mean.npz', lr=0.0001, mode='sample', num_domains=2, num_outs_per_domain=10, num_workers=4, out_dir='assets/representative/celeba_hq/src/female', print_every=10, randcrop_prob=0.5, ref_dir='my_experiment/ref', result_dir='my_experiment/results', resume_iter=100000, sample_dir='expr/samples', sample_every=5000, save_every=10000, seed=777, src_dir='my_experiment/src', style_dim=64, total_iters=100000, train_img_dir='data/celeba_hq/train', val_batch_size=32, val_img_dir='data/celeba_hq/val', w_hpf=1.0, weight_decay=0.0001, wing_path='expr/checkpoints/wing.ckpt')
Number of parameters of generator: 43467395
Number of parameters of mapping_network: 2438272

H.shape before: torch.Size([2, 512, 1, 1])
H.shape after: torch.Size([2, 512])
len(out) before: 2
out.shape after: torch.Size([2, 2, 64])
OUT: tensor([[[ 1.1713, -1.1371,  0.2181, -0.2989, -0.7462,  0.3311,  0.5409,
           1.6859,  1.7946, -0.4707, -1.5976, -1.6116, -0.8940,  0.8856,
           0.1836, -0.4243,  1.5599,  0.0772, -0.8860,  1.0079,  0.5985,
          -1.1520,  0.9832, -1.3237,  0.4058,  0.1356,  1.1079, -0.8748,
           1.6796, -0.5946, -0.6884,  0.5382, -1.3920, -0.8834,  1.6290,
          -0.6876,  0.0090,  1.6941, -0.4298,  0.1530, -2.2129,  0.9818,
          -1.2147, -1.1813, -0.5949, -0.4926, -0.9399, -0.3763,  0.4755,
          -2.0352, -1.7954,  0.1015,  0.5432,  0.1582,  0.6301,  0.9467,
          -1.4342, -1.3404,  1.9331, -1.5649,  0.1566,  1.0164, -1.9589,
          -0.4186],
         [-0.3219, -1.4319, -0.3994,  1.4013, -0.0781,  0.4606,  0.9882,
           1.1066, -1.8467,  0.1585,  1.7096, -1.6057,  0.8242,  0.2532,
           0.6031,  0.3341, -0.745

# With avg faces aligned

In [12]:
!python main.py --mode sample --num_domains 2 --resume_iter 100000 --w_hpf 1 \
                --checkpoint_dir expr/checkpoints/celeba_hq \
                --result_dir my_experiment/results \
                --src_dir my_experiment/src \
                --ref_dir my_experiment/ref

Namespace(batch_size=8, beta1=0.0, beta2=0.99, checkpoint_dir='expr/checkpoints/celeba_hq', ds_iter=100000, eval_dir='expr/eval', eval_every=50000, f_lr=1e-06, hidden_dim=512, img_size=256, inp_dir='assets/representative/custom/female', lambda_cyc=1, lambda_ds=1, lambda_reg=1, lambda_sty=1, latent_dim=16, lm_path='expr/checkpoints/celeba_lm_mean.npz', lr=0.0001, mode='sample', num_domains=2, num_outs_per_domain=10, num_workers=4, out_dir='assets/representative/celeba_hq/src/female', print_every=10, randcrop_prob=0.5, ref_dir='my_experiment/ref', result_dir='my_experiment/results', resume_iter=100000, sample_dir='expr/samples', sample_every=5000, save_every=10000, seed=777, src_dir='my_experiment/src', style_dim=64, total_iters=100000, train_img_dir='data/celeba_hq/train', val_batch_size=32, val_img_dir='data/celeba_hq/val', w_hpf=1.0, weight_decay=0.0001, wing_path='expr/checkpoints/wing.ckpt')
Number of parameters of generator: 43467395
Number of parameters of mapping_network: 2438272

In [14]:
import torch

In [17]:
myrand = torch.rand(2,2,64)
myrand.shape

torch.Size([2, 2, 64])

In [18]:
myrand

tensor([[[0.7793, 0.3772, 0.4308, 0.3869, 0.5443, 0.4000, 0.4574, 0.5934,
          0.1729, 0.0755, 0.4928, 0.6684, 0.7016, 0.1845, 0.3060, 0.9569,
          0.2110, 0.7333, 0.3520, 0.3173, 0.3193, 0.1222, 0.7255, 0.3517,
          0.6050, 0.2843, 0.1982, 0.4004, 0.1843, 0.6621, 0.8105, 0.6392,
          0.9831, 0.3116, 0.5312, 0.2806, 0.3168, 0.9464, 0.5875, 0.8133,
          0.1055, 0.3122, 0.4302, 0.9097, 0.9343, 0.9893, 0.9850, 0.3345,
          0.4819, 0.2236, 0.0819, 0.0367, 0.0435, 0.5614, 0.2986, 0.0892,
          0.8893, 0.3656, 0.8465, 0.8617, 0.3651, 0.5198, 0.5578, 0.0386],
         [0.9484, 0.7974, 0.9653, 0.3330, 0.9607, 0.3231, 0.7316, 0.2038,
          0.2111, 0.0964, 0.5475, 0.1617, 0.8815, 0.7566, 0.4892, 0.5627,
          0.4429, 0.1831, 0.5331, 0.8958, 0.3032, 0.2912, 0.8584, 0.3405,
          0.1537, 0.1266, 0.8241, 0.1835, 0.9775, 0.4292, 0.4751, 0.7782,
          0.7757, 0.7318, 0.7579, 0.9410, 0.1495, 0.2643, 0.8352, 0.4293,
          0.5662, 0.0732, 0.1222, 0.6

In [19]:
myrand[torch.tensor([0,1])]

tensor([[[0.7793, 0.3772, 0.4308, 0.3869, 0.5443, 0.4000, 0.4574, 0.5934,
          0.1729, 0.0755, 0.4928, 0.6684, 0.7016, 0.1845, 0.3060, 0.9569,
          0.2110, 0.7333, 0.3520, 0.3173, 0.3193, 0.1222, 0.7255, 0.3517,
          0.6050, 0.2843, 0.1982, 0.4004, 0.1843, 0.6621, 0.8105, 0.6392,
          0.9831, 0.3116, 0.5312, 0.2806, 0.3168, 0.9464, 0.5875, 0.8133,
          0.1055, 0.3122, 0.4302, 0.9097, 0.9343, 0.9893, 0.9850, 0.3345,
          0.4819, 0.2236, 0.0819, 0.0367, 0.0435, 0.5614, 0.2986, 0.0892,
          0.8893, 0.3656, 0.8465, 0.8617, 0.3651, 0.5198, 0.5578, 0.0386],
         [0.9484, 0.7974, 0.9653, 0.3330, 0.9607, 0.3231, 0.7316, 0.2038,
          0.2111, 0.0964, 0.5475, 0.1617, 0.8815, 0.7566, 0.4892, 0.5627,
          0.4429, 0.1831, 0.5331, 0.8958, 0.3032, 0.2912, 0.8584, 0.3405,
          0.1537, 0.1266, 0.8241, 0.1835, 0.9775, 0.4292, 0.4751, 0.7782,
          0.7757, 0.7318, 0.7579, 0.9410, 0.1495, 0.2643, 0.8352, 0.4293,
          0.5662, 0.0732, 0.1222, 0.6

In [20]:
myrand[torch.tensor([0,1]), [0,1]]

tensor([[0.7793, 0.3772, 0.4308, 0.3869, 0.5443, 0.4000, 0.4574, 0.5934, 0.1729,
         0.0755, 0.4928, 0.6684, 0.7016, 0.1845, 0.3060, 0.9569, 0.2110, 0.7333,
         0.3520, 0.3173, 0.3193, 0.1222, 0.7255, 0.3517, 0.6050, 0.2843, 0.1982,
         0.4004, 0.1843, 0.6621, 0.8105, 0.6392, 0.9831, 0.3116, 0.5312, 0.2806,
         0.3168, 0.9464, 0.5875, 0.8133, 0.1055, 0.3122, 0.4302, 0.9097, 0.9343,
         0.9893, 0.9850, 0.3345, 0.4819, 0.2236, 0.0819, 0.0367, 0.0435, 0.5614,
         0.2986, 0.0892, 0.8893, 0.3656, 0.8465, 0.8617, 0.3651, 0.5198, 0.5578,
         0.0386],
        [0.5238, 0.6846, 0.0329, 0.4335, 0.0569, 0.4047, 0.4386, 0.8216, 0.3981,
         0.6476, 0.1804, 0.6916, 0.1046, 0.0135, 0.5037, 0.5543, 0.8378, 0.8621,
         0.8899, 0.7728, 0.4248, 0.0203, 0.8497, 0.4720, 0.7846, 0.6528, 0.3748,
         0.1865, 0.1892, 0.0495, 0.4485, 0.3090, 0.8198, 0.7973, 0.1694, 0.9552,
         0.0800, 0.4037, 0.7752, 0.4408, 0.6833, 0.7786, 0.5245, 0.1071, 0.5514,
         0

In [5]:
yy = [1,2]
yy

[1, 2]

In [6]:
import numpy as np

In [7]:
new_yy = np.asarray(yy) - 1
new_yy

array([0, 1])

In [8]:
list(new_yy)

[0, 1]

In [22]:
myrand[torch.tensor([0,1]), yy]

IndexError: index 2 is out of bounds for dimension 1 with size 2

In [23]:
myrand[torch.tensor([0,1]), new_yy]

tensor([[0.7793, 0.3772, 0.4308, 0.3869, 0.5443, 0.4000, 0.4574, 0.5934, 0.1729,
         0.0755, 0.4928, 0.6684, 0.7016, 0.1845, 0.3060, 0.9569, 0.2110, 0.7333,
         0.3520, 0.3173, 0.3193, 0.1222, 0.7255, 0.3517, 0.6050, 0.2843, 0.1982,
         0.4004, 0.1843, 0.6621, 0.8105, 0.6392, 0.9831, 0.3116, 0.5312, 0.2806,
         0.3168, 0.9464, 0.5875, 0.8133, 0.1055, 0.3122, 0.4302, 0.9097, 0.9343,
         0.9893, 0.9850, 0.3345, 0.4819, 0.2236, 0.0819, 0.0367, 0.0435, 0.5614,
         0.2986, 0.0892, 0.8893, 0.3656, 0.8465, 0.8617, 0.3651, 0.5198, 0.5578,
         0.0386],
        [0.5238, 0.6846, 0.0329, 0.4335, 0.0569, 0.4047, 0.4386, 0.8216, 0.3981,
         0.6476, 0.1804, 0.6916, 0.1046, 0.0135, 0.5037, 0.5543, 0.8378, 0.8621,
         0.8899, 0.7728, 0.4248, 0.0203, 0.8497, 0.4720, 0.7846, 0.6528, 0.3748,
         0.1865, 0.1892, 0.0495, 0.4485, 0.3090, 0.8198, 0.7973, 0.1694, 0.9552,
         0.0800, 0.4037, 0.7752, 0.4408, 0.6833, 0.7786, 0.5245, 0.1071, 0.5514,
         0